export const stemRed = '#B31312';
export const stemRedDark = '#8B0000';
export const sidebarBg = '#222222';

export const getAdminStyles = (isMobile, isSidebarCollapsed, isSidebarOpen) => {
  const sidebarWidth = isMobile ? '260px' : (isSidebarCollapsed ? '80px' : '240px');

  return {
    dashboardContainer: { display: 'flex', height: '100vh', overflow: 'hidden', backgroundColor: '#f3f6fb', fontFamily: '"Montserrat", "Inter", system-ui, sans-serif' },
    sidebar: {
      width: sidebarWidth,
      minWidth: sidebarWidth,
      backgroundColor: sidebarBg,
      color: 'white',
      display: 'flex',
      flexDirection: 'column',
      position: isMobile ? 'fixed' : 'relative',
      height: '100vh',
      zIndex: 1000,
      left: isMobile ? (isSidebarOpen ? '0' : '-260px') : '0',
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      overflowY: 'visible',
      overflowX: 'visible',
      borderRight: '1px solid rgba(255,255,255,0.05)',
    },
    sidebarContent: {
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      overflowY: 'auto',
      overflowX: 'hidden',
    },
    sidebarOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', zIndex: 999 },
    logoBox: {
      padding: isSidebarCollapsed ? '16px 0' : '16px 20px',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      borderBottom: '1px solid rgba(255,255,255,0.05)',
      height: '72px',
      boxSizing: 'border-box',
    },
    menuList: { listStyle: 'none', padding: 0, margin: 0, flex: 1, marginTop: '8px' },
    menuItem: { padding: '12px 20px', cursor: 'pointer', borderLeft: '3px solid transparent', color: '#cbd5e1', fontSize: '12px', transition: 'all 0.2s', display: 'flex', alignItems: 'center', justifyContent: isSidebarCollapsed ? 'center' : 'space-between', fontWeight: '600' },
    menuItemActive: { padding: '12px 20px', cursor: 'pointer', backgroundColor: 'rgba(255,255,255,0.04)', fontWeight: '800', borderLeft: `3px solid ${stemRed}`, color: 'white', display: 'flex', alignItems: 'center', justifyContent: isSidebarCollapsed ? 'center' : 'space-between' },
    menuContent: { display: 'flex', alignItems: 'center', gap: isSidebarCollapsed ? '0' : '10px', justifyContent: isSidebarCollapsed ? 'center' : 'flex-start', width: '100%' },
    categoryLabel: { color: '#64748b', fontSize: '9px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '2px', padding: '20px 20px 8px 20px', display: 'block' },
    collapsedDivider: { height: '1px', backgroundColor: 'rgba(255,255,255,0.1)', margin: '15px 20px' },
    notificationBadge: { backgroundColor: stemRed, color: 'white', padding: '2px 6px', borderRadius: '999px', fontSize: '9px', fontWeight: 'bold', position: isSidebarCollapsed ? 'absolute' : 'relative', top: isSidebarCollapsed ? '10px' : 'auto', right: isSidebarCollapsed ? '20px' : 'auto' },
    logoutBtn: { margin: isSidebarCollapsed ? '20px 10px' : '20px', padding: '12px', backgroundColor: 'transparent', color: '#ef4444', border: '1px solid #ef4444', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', fontSize: '12px', textAlign: 'center', transition: '0.2s', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: isSidebarCollapsed ? '0' : '8px' },
    rightWrapper: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', width: isMobile ? '100%' : `calc(100% - ${sidebarWidth})`, minWidth: 0, transition: 'all 0.3s' },
    topHeader: {
      display: isMobile ? 'none' : 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '8px 24px',
      backgroundColor: '#ffffff',
      borderBottom: '1px solid #e2e8f0',
      zIndex: 10,
      height: '60px',
      boxSizing: 'border-box',
    },
    mainContent: { flex: 1, padding: isMobile ? '12px 10px 18px' : '22px', overflowY: 'auto', overflowX: 'hidden', backgroundColor: '#f3f6fb' },
    mobileHeader: { display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px', backgroundColor: 'white', padding: '10px 12px', borderRadius: '12px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)', position: 'sticky', top: 0, zIndex: 60 },
    hamburgerBtn: { background: 'none', border: '1px solid #e2e8f0', borderRadius: '8px', padding: '8px', width: '42px', height: '42px', cursor: 'pointer', backgroundColor: '#f8fafc', color: stemRed, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
    searchContainer: { display: 'flex', alignItems: 'center', backgroundColor: 'white', padding: '0 14px', borderRadius: '12px', boxShadow: '0 7px 18px rgba(15, 23, 42, 0.05)', border: '1px solid #e8eef7', flex: 1, height: '40px' },
    searchInput: { border: 'none', outline: 'none', width: '100%', minWidth: 0, fontSize: '12px', backgroundColor: 'transparent', color: '#334155', fontFamily: 'inherit', marginLeft: '10px', fontWeight: '700' },
    heroBanner: { backgroundColor: stemRed, padding: isMobile ? '18px' : '30px', borderRadius: '12px', boxShadow: '0 10px 15px -3px rgba(179, 19, 18, 0.3)', marginBottom: isMobile ? '16px' : '30px', color: 'white', backgroundImage: 'linear-gradient(135deg, #B31312 0%, #8B0000 100%)' },
    heroTitle: { margin: 0, fontSize: isMobile ? '24px' : '28px', color: '#fff', fontWeight: '700' },
    heroSubtitle: { margin: '8px 0 0 0', color: '#f8fafc', fontSize: '15px', opacity: 0.9 },
    headerCard: { backgroundColor: 'white', padding: isMobile ? '18px' : '30px', borderRadius: '12px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)', marginBottom: isMobile ? '16px' : '30px', borderLeft: `6px solid ${stemRed}` },
    card: { backgroundColor: 'white', padding: isMobile ? '16px' : '20px', borderRadius: '14px', boxShadow: '0 12px 28px rgba(15, 23, 42, 0.055)', border: '1px solid #e8eef7', marginBottom: '22px' },
    labelStyle: { fontSize: '12px', fontWeight: '800', marginBottom: '7px', display: 'block', color: '#334155' },
    modernInput: { width: '100%', minWidth: 0, padding: '10px 13px', border: '1px solid #cbd5e1', borderRadius: '8px', boxSizing: 'border-box', backgroundColor: '#f8fafc', fontSize: isMobile ? '16px' : '13px', fontFamily: '"Montserrat", sans-serif' },
    inputStyle: { width: '100%', padding: '10px', border: '2px dashed #cbd5e1', borderRadius: '8px', backgroundColor: '#f8fafc', marginTop: '5px', fontSize: '12px', cursor: 'pointer', fontFamily: '"Montserrat", sans-serif' },
    jobCard: { backgroundColor: 'white', padding: isMobile ? '20px' : '30px', borderRadius: '12px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)', border: '1px solid #e2e8f0', transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)', display: 'flex', flexDirection: 'column' },
    jobCardHeader: { display: 'flex', flexDirection: isMobile ? 'column' : 'row', justifyContent: 'space-between', alignItems: isMobile ? 'flex-start' : 'flex-start', gap: '15px' },
    btnPrimary: { padding: '10px 16px', backgroundColor: stemRed, color: 'white', border: 'none', borderRadius: '8px', fontWeight: '700', cursor: 'pointer', transition: 'all 0.2s', width: isMobile ? '100%' : 'auto', textAlign: 'center', fontSize: '12px', fontFamily: '"Montserrat", sans-serif', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' },
    btnDanger: { padding: '10px 15px', backgroundColor: '#dc2626', color: 'white', border: 'none', borderRadius: '6px', fontWeight: 'bold', cursor: 'pointer', fontSize: '13px', fontFamily: '"Montserrat", sans-serif' },
    btnAction: { padding: '8px 14px', backgroundColor: stemRedDark, color: 'white', border: 'none', borderRadius: '6px', fontSize: '13px', cursor: 'pointer', fontWeight: '600', fontFamily: '"Montserrat", sans-serif', display: 'flex', alignItems: 'center', gap: '6px', justifyContent: 'center' },
    btnSuccess: { padding: '10px 16px', backgroundColor: '#10b981', color: 'white', border: 'none', borderRadius: '8px', fontSize: '13px', cursor: 'pointer', fontWeight: '700', transition: 'all 0.2s', boxShadow: '0 2px 4px rgba(16, 185, 129, 0.2)', fontFamily: '"Montserrat", sans-serif', display: 'flex', alignItems: 'center', gap: '6px', justifyContent: 'center' },
    linkDoc: { color: stemRed, textDecoration: 'none', fontSize: '12px', backgroundColor: '#fef2f2', padding: '6px 12px', borderRadius: '6px', display: 'inline-flex', alignItems: 'center', gap: '6px', fontWeight: '700', border: '1px solid #fecaca' },
    table: { width: '100%', borderCollapse: 'separate', borderSpacing: 0, marginTop: '8px', minWidth: isMobile ? '760px' : '880px' },
    th: { backgroundColor: '#f8fafc', padding: '12px 14px', textAlign: 'left', fontSize: '10px', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.7px', borderBottom: '1px solid #edf2f7', fontWeight: '900' },
    td: { padding: '12px 14px', borderBottom: '1px solid #f1f5f9', fontSize: '12px', color: '#334155', verticalAlign: 'middle' },
    tr: { transition: 'background-color 0.2s' },
    badgeSuccess: { backgroundColor: '#dcfce7', color: '#166534', padding: '6px 12px', borderRadius: '20px', fontSize: '12px', fontWeight: 'bold', display: 'inline-flex', alignItems: 'center', gap: '4px', border: '1px solid #bbf7d0' },
    badgeDanger: { backgroundColor: '#fee2e2', color: '#991b1b', padding: '6px 12px', borderRadius: '20px', fontSize: '12px', fontWeight: 'bold', display: 'inline-flex', alignItems: 'center', gap: '4px', border: '1px solid #fecaca' },
    badgeWarning: { backgroundColor: '#fef3c7', color: '#92400e', padding: '6px 12px', borderRadius: '20px', fontSize: '12px', fontWeight: 'bold', display: 'inline-flex', alignItems: 'center', gap: '4px', border: '1px solid #fde68a' },
    modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(15, 23, 42, 0.7)', backdropFilter: 'blur(4px)', display: 'flex', justifyContent: 'center', alignItems: isMobile ? 'flex-start' : 'center', zIndex: 1000, padding: isMobile ? '12px' : '0', overflowY: 'auto' },
    modalContent: { backgroundColor: 'white', width: isMobile ? '100%' : '90%', maxWidth: '800px', borderRadius: '16px', boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)', overflow: 'hidden', display: 'flex', flexDirection: 'column', maxHeight: isMobile ? 'calc(100vh - 24px)' : '90vh' },
    modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '12px', padding: isMobile ? '16px 18px' : '20px 30px', backgroundColor: '#fff', borderBottom: '1px solid #e2e8f0' },
    modalFooter: { display: 'flex', flexDirection: isMobile ? 'column' : 'row', justifyContent: 'flex-end', gap: '12px', padding: isMobile ? '16px 18px' : '20px 30px', backgroundColor: '#f8fafc', borderTop: '1px solid #e2e8f0' },
    grid2Modal: { display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: isMobile ? '14px' : '30px' },
  };
};
