# Generated by Django 6.0.1 on 2026-02-20 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_vacancy_placement_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.CharField(max_length=100)),
                ('company_profile', models.TextField(verbose_name='Profil Perusahaan')),
                ('job_description', models.TextField(verbose_name='Jobdesk')),
                ('work_environment', models.TextField(verbose_name='Suasana Lingkungan Pekerjaan')),
                ('useful_courses', models.TextField(verbose_name='Apa yang didapatkan dari perkuliahan yang berguna')),
                ('new_skills', models.TextField(verbose_name='Hal berguna di perusahaan tapi belum didapat di kampus')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
