# Generated by Django 6.0.1 on 2026-02-20 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_type', models.CharField(choices=[('UTS', 'Laporan Kemajuan (UTS)'), ('UAS', 'Laporan Akhir (UAS)')], max_length=3)),
                ('is_filled', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Nilai (0-100)')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Komentar / Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.placement')),
            ],
        ),
    ]
