# Generated by Django 6.0.1 on 2026-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_supervisorevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uts_template', models.FileField(blank=True, null=True, upload_to='templates_doc/')),
                ('uas_template', models.FileField(blank=True, null=True, upload_to='templates_doc/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
