# Generated by Django 6.0.1 on 2026-03-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
