# Generated by Django 6.0.1 on 2026-03-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_placement_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyHuntReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.CharField(max_length=50)),
                ('companies_applied', models.TextField(verbose_name='Perusahaan yang dilamar minggu ini')),
                ('challenges', models.TextField(verbose_name='Kendala yang dihadapi')),
                ('next_plan', models.TextField(verbose_name='Rencana minggu depan')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
