# Generated by Django 6.0.1 on 2026-03-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_weeklyhuntreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Review'), ('reviewed', 'Telah Diteruskan ke HRD'), ('accepted', 'Diterima Perusahaan'), ('rejected', 'Ditolak Perusahaan')], default='pending', max_length=20),
        ),
    ]
