# Generated by Django 6.0.1 on 2026-03-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_utsreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_subject', models.CharField(default='Mohon Evaluasi Kinerja Magang', max_length=255)),
                ('eval_message', models.TextField(default='Halo Supervisor, mohon isi evaluasi mahasiswa kami.')),
            ],
        ),
    ]
