# Generated by Django 6.0.1 on 2026-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_emailsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
