# Generated by Django 6.0.1 on 2026-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_vacancy_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='external_apply_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
