# Generated by Django 6.0.1 on 2026-04-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_vacancy_external_apply_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('verified', 'Terverifikasi (Aktif)'), ('resigned', 'Pindah Tempat / Berhenti'), ('rejected', 'Ditolak Admin'), ('completed', 'Selesai Magang')], default='pending', max_length=20),
        ),
    ]
