"""
Django settings for coop_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote_plus

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import dotenv_values, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR / '.env'
ENV_FILE_VALUES = dotenv_values(ENV_FILE)
load_dotenv(ENV_FILE)


def parse_bool(value, default=False):
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_bool(name, default=False):
    return parse_bool(os.getenv(name), default)


def env_list(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


def env_file_value(name, default=None):
    value = ENV_FILE_VALUES.get(name)
    if value in (None, ''):
        return default
    return value


def env_first(*names, default=None):
    for name in names:
        value = os.getenv(name)
        if value not in (None, ''):
            return value
    return default


def build_postgres_url_from_env():
    host = env_first('POSTGRES_HOST', 'PGHOST', default='127.0.0.1')
    port = env_first('POSTGRES_PORT', 'PGPORT', default='5432')
    name = env_first('POSTGRES_DB', 'PGDATABASE')
    user = env_first('POSTGRES_USER', 'PGUSER')
    password = env_first('POSTGRES_PASSWORD', 'PGPASSWORD')

    if not all([name, user]):
        return None

    if password in (None, ''):
        raise ImproperlyConfigured(
            'Password PostgreSQL belum diisi. '
            'Set DATABASE_URL lengkap atau isi POSTGRES_PASSWORD/PGPASSWORD di file .env.'
        )

    return (
        'postgresql://'
        f'{quote_plus(user)}:{quote_plus(password)}@{host}:{port}/{quote_plus(name)}'
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    env_first('DJANGO_SECRET_KEY')
    or env_file_value('SECRET_KEY')
    or 'django-insecure-dev-only-change-me'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = parse_bool(os.getenv('DJANGO_DEBUG'), parse_bool(env_file_value('DEBUG'), True))

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken', 
    'corsheaders',              
    'core_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coop_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coop_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DEFAULT_SQLITE_URL = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
USE_SQLITE_FOR_LOCAL_DEV = parse_bool(
    os.getenv('DJANGO_USE_SQLITE'),
    parse_bool(env_file_value('USE_SQLITE'), False),
)
DATABASE_URL = (
    env_first('DATABASE_URL')
    or env_file_value('DATABASE_URL')
    or build_postgres_url_from_env()
)

if USE_SQLITE_FOR_LOCAL_DEV:
    DATABASE_URL = DEFAULT_SQLITE_URL
elif not DATABASE_URL:
    raise ImproperlyConfigured(
        'Konfigurasi database belum lengkap. '
        'Isi DATABASE_URL atau pasangan POSTGRES_DB, POSTGRES_USER, dan POSTGRES_PASSWORD. '
        'Atau set DJANGO_USE_SQLITE=true untuk mode SQLite lokal.'
    )

DB_CONN_MAX_AGE = 0 if DEBUG else int(env_first('DJANGO_DB_CONN_MAX_AGE', default='600'))
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=DB_CONN_MAX_AGE, ssl_require=False),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- SETTING REACT (CORS) ---
CORS_ALLOW_ALL_ORIGINS = env_bool('DJANGO_CORS_ALLOW_ALL_ORIGINS', DEBUG)
CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)

# --- CUSTOM USER MODEL ---
AUTH_USER_MODEL = 'core_app.User'

# --- SETTING UPLOAD FILE (PDF/Gambar) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# ==========================================
# SETTING DJANGO REST FRAMEWORK (AUTH)
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', 
        'rest_framework.authentication.SessionAuthentication',
    ],
}


# ==========================================
# KONFIGURASI EMAIL (Via Outlook / Office 365)
# ==========================================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.office365.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

default_sender = EMAIL_HOST_USER or 'no-reply@coop.local'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', f'Admin Co-op Prasmul <{default_sender}>')
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'http://localhost:5173')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
