export const GLOBAL_STYLES = `
  @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap');
  .job-card { transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); border: 1px solid #e2e8f0; border-radius: 16px; background: white; overflow: hidden; display: flex; flex-direction: column; }
  .job-card:hover { transform: translateY(-6px); box-shadow: 0 20px 25px -5px rgba(0, 51, 102, 0.1), 0 8px 10px -6px rgba(0, 51, 102, 0.1); border-color: #F2A900; }
  .job-card-header { padding: 20px; border-bottom: 1px solid #f1f5f9; background: linear-gradient(to right, #ffffff, #f8fafc); }
  .job-card-body { padding: 20px; flex: 1; display: flex; flex-direction: column; }
  .timeline-item { position: relative; padding-left: 30px; margin-bottom: 25px; }
  .timeline-item::before { content: ''; position: absolute; left: 6px; top: 0; bottom: -25px; width: 2px; background-color: #e2e8f0; }
  .timeline-item:last-child::before { display: none; }
  .timeline-dot { position: absolute; left: 0; top: 5px; width: 14px; height: 14px; border-radius: 50%; background-color: #F2A900; border: 3px solid #fff; box-shadow: 0 0 0 2px #e2e8f0; z-index: 1; }
  @keyframes spin { 100% { transform: rotate(360deg); } }
  .animate-spin { animation: spin 1s linear infinite; }
  .btn-hover:hover { opacity: 0.9; transform: scale(0.98); }
  .input-focus:focus { border-color: #003366 !important; box-shadow: 0 0 0 3px rgba(0, 51, 102, 0.1) !important; }
  .responsive-table-wrap { width: 100%; overflow-x: auto; -webkit-overflow-scrolling: touch; }
  .mobile-safe-text { overflow-wrap: anywhere; }
  @media (max-width: 768px) {
    input, select, textarea { font-size: 16px !important; }
    .job-card:hover { transform: none; }
    .job-card { border-radius: 14px; }
    .job-card-header { padding: 16px; }
    .job-card-body { padding: 16px; }
    .timeline-item { padding-left: 24px; margin-bottom: 18px; }
    .timeline-item::before { bottom: -18px; }
    .btn-hover:hover { transform: none; }
  }
  @media print {
    body * { visibility: hidden; }
    .printable-certificate, .printable-certificate * { visibility: visible; }
    .printable-certificate { position: absolute; left: 0; top: 0; width: 100%; margin: 0; box-shadow: none !important; border: none !important; }
    .no-print { display: none !important; }
  }
`;

export const MOBILE_BREAKPOINT = 768;
export const PRASMUL_LOGO_URL = '/logo-prasmul.png';
export const COLLAPSED_SECTION_LABEL = '•••';
export const INDONESIAN_DATE_FORMAT = { day: 'numeric', month: 'short', year: 'numeric' };

export const getDashboardStyles = (isMobile, isSidebarOpen, isSidebarCollapsed) => ({
  dashboardContainer: {
    display: 'flex',
    height: '100vh',
    overflow: 'hidden',
    backgroundColor: '#f8fafc',
    fontFamily: '"Montserrat", "Inter", system-ui, sans-serif',
    position: 'relative',
  },
  sidebar: {
    width: isMobile ? '260px' : isSidebarCollapsed ? '88px' : '260px',
    backgroundColor: '#003366',
    color: 'white',
    display: 'flex',
    flexDirection: 'column',
    position: isMobile ? 'fixed' : 'relative',
    height: '100vh',
    zIndex: 1000,
    left: isMobile ? (isSidebarOpen ? '0' : '-260px') : '0',
    transition: 'all 0.3s ease-in-out',
  },
  sidebarContent: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  collapseBtn: {
    position: 'absolute',
    right: '-14px',
    top: '38px',
    backgroundColor: '#fff',
    color: '#003366',
    border: '1px solid #cbd5e1',
    borderRadius: '50%',
    width: '28px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    zIndex: 1001,
    boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)',
    transition: 'all 0.2s',
  },
  sidebarOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 999,
  },
  logoBox: {
    padding: '30px 20px 20px 20px',
    borderBottom: '1px solid #002244',
    textAlign: 'center',
    transition: 'all 0.3s ease',
    minHeight: '85px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuList: { listStyle: 'none', padding: 0, margin: 0, flex: 1 },
  menuItem: {
    padding: isSidebarCollapsed && !isMobile ? '16px 0' : '14px 20px',
    justifyContent: isSidebarCollapsed && !isMobile ? 'center' : 'flex-start',
    cursor: 'pointer',
    borderLeft: '4px solid transparent',
    color: '#cbd5e1',
    fontSize: '14px',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    fontWeight: '500',
  },
  menuItemActive: {
    padding: isSidebarCollapsed && !isMobile ? '16px 0' : '14px 20px',
    justifyContent: isSidebarCollapsed && !isMobile ? 'center' : 'flex-start',
    cursor: 'pointer',
    backgroundColor: '#002244',
    fontWeight: '700',
    borderLeft: '4px solid #F2A900',
    color: '#F2A900',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  menuText: {
    display: isSidebarCollapsed && !isMobile ? 'none' : 'block',
    whiteSpace: 'nowrap',
  },
  newBadge: {
    backgroundColor: '#ef4444',
    color: 'white',
    fontSize: '10px',
    padding: '2px 8px',
    borderRadius: '12px',
    marginLeft: 'auto',
    fontWeight: 'bold',
  },
  logoutBtn: {
    width: '100%',
    padding: '14px',
    backgroundColor: 'transparent',
    color: '#F2A900',
    border: '1px solid #F2A900',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 'bold',
    transition: '0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    boxSizing: 'border-box',
  },
  mainContent: {
    flex: 1,
    padding: isMobile ? '10px 10px max(20px, env(safe-area-inset-bottom))' : '40px',
    overflowY: 'auto',
    overflowX: 'hidden',
    width: '100%',
    minWidth: 0,
    backgroundColor: isMobile ? '#eef2f7' : '#f8fafc',
  },
  mobileHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '10px',
    backgroundColor: 'white',
    padding: '10px 12px',
    borderRadius: '14px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 10px 24px rgba(15, 23, 42, 0.08)',
    position: 'sticky',
    top: 0,
    zIndex: 60,
  },
  hamburgerBtn: {
    background: 'none',
    border: '1px solid #e2e8f0',
    borderRadius: '11px',
    padding: 0,
    width: '42px',
    height: '42px',
    cursor: 'pointer',
    backgroundColor: '#f8fafc',
    color: '#003366',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroBanner: {
    backgroundColor: '#003366',
    padding: isMobile ? '18px 16px' : '30px',
    borderRadius: isMobile ? '16px' : '12px',
    boxShadow: isMobile ? '0 14px 30px rgba(0, 51, 102, 0.16)' : '0 4px 6px -1px rgba(0,0,0,0.05)',
    marginBottom: isMobile ? '14px' : '30px',
    color: 'white',
    overflow: 'hidden',
  },
  heroTitle: {
    margin: 0,
    fontSize: isMobile ? '21px' : '28px',
    color: '#fff',
    fontWeight: '800',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    lineHeight: 1.2,
    overflowWrap: 'anywhere',
  },
  heroSubtitle: {
    margin: '8px 0 0 0',
    color: '#e2e8f0',
    fontSize: isMobile ? '13px' : '15px',
    lineHeight: 1.55,
  },
  headerCard: {
    backgroundColor: 'white',
    padding: isMobile ? '20px' : '30px',
    borderRadius: '12px',
    boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)',
    marginBottom: isMobile ? '18px' : '30px',
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: isMobile ? '1fr' : 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: isMobile ? '14px' : '20px',
  },
  card: {
    backgroundColor: 'white',
    padding: isMobile ? '16px' : '30px',
    borderRadius: isMobile ? '14px' : '12px',
    boxShadow: isMobile ? '0 10px 24px rgba(15, 23, 42, 0.055)' : '0 4px 6px -1px rgba(0,0,0,0.05)',
    border: '1px solid #e2e8f0',
    minWidth: 0,
  },
  textLabel: {
    fontSize: '12px',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    fontWeight: 'bold',
  },
  textValue: {
    margin: '4px 0 0 0',
    fontSize: '15px',
    color: '#003366',
    fontWeight: '600',
  },
  sectionTitle: {
    margin: isMobile ? '20px 0 12px 0' : '25px 0 15px 0',
    color: '#003366',
    fontSize: isMobile ? '15px' : '16px',
    borderBottom: '1px solid #e2e8f0',
    paddingBottom: '8px',
    fontWeight: '700',
  },
  inputStyle: {
    width: '100%',
    padding: '12px 15px',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    boxSizing: 'border-box',
    fontSize: isMobile ? '16px' : '14px',
    outline: 'none',
    transition: 'all 0.2s',
    fontFamily: '"Montserrat", sans-serif',
  },
  fileInput: {
    width: '100%',
    padding: '12px',
    border: '2px dashed #cbd5e1',
    borderRadius: '8px',
    backgroundColor: '#f8fafc',
    marginTop: '5px',
    fontSize: isMobile ? '16px' : '13px',
    cursor: 'pointer',
    fontFamily: '"Montserrat", sans-serif',
  },
  btnPrimary: {
    padding: '12px 20px',
    backgroundColor: '#003366',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontSize: '14px',
    fontFamily: '"Montserrat", sans-serif',
    width: isMobile ? '100%' : 'auto',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },
  labelStyle: {
    fontSize: '13px',
    fontWeight: '700',
    marginBottom: '8px',
    display: 'block',
    color: '#334155',
  },
  alertWarning: {
    padding: isMobile ? '14px' : '15px 20px',
    backgroundColor: '#fffbeb',
    borderLeft: '4px solid #F2A900',
    borderRadius: '8px',
    marginBottom: isMobile ? '14px' : '25px',
    display: 'flex',
    gap: isMobile ? '11px' : '15px',
    alignItems: 'flex-start',
  },
  alertDanger: {
    padding: isMobile ? '14px' : '15px 20px',
    backgroundColor: '#fee2e2',
    borderLeft: '4px solid #ef4444',
    borderRadius: '8px',
    marginBottom: isMobile ? '14px' : '25px',
    display: 'flex',
    gap: isMobile ? '11px' : '15px',
    alignItems: 'flex-start',
  },
  badgeSuccess: {
    backgroundColor: '#e6f0fa',
    color: '#003366',
    padding: '6px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: 'bold',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  badgeDanger: {
    backgroundColor: '#fee2e2',
    color: '#991b1b',
    padding: '6px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: 'bold',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 51, 102, 0.7)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: isMobile ? 'flex-start' : 'center',
    zIndex: 1000,
    backdropFilter: 'blur(4px)',
    padding: isMobile ? '12px' : '0',
    overflowY: 'auto',
  },
  modalContent: {
    backgroundColor: 'white',
    width: isMobile ? '100%' : '90%',
    maxWidth: '750px',
    borderRadius: '16px',
    boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: isMobile ? 'calc(100vh - 24px)' : '90vh',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    padding: isMobile ? '16px 18px' : '20px 30px',
    backgroundColor: '#fff',
    borderBottom: '1px solid #e2e8f0',
  },
  modalFooter: {
    display: 'flex',
    flexDirection: isMobile ? 'column' : 'row',
    justifyContent: 'flex-end',
    gap: '12px',
    padding: isMobile ? '16px 18px' : '20px 30px',
    backgroundColor: '#f8fafc',
    borderTop: '1px solid #e2e8f0',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#94a3b8',
    transition: '0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  certificateBox: {
    backgroundColor: '#fff',
    padding: isMobile ? '20px' : '40px',
    borderRadius: '12px',
    border: '8px double #F2A900',
    textAlign: 'center',
    boxShadow: '0 10px 30px rgba(0, 51, 102, 0.1)',
    backgroundImage: 'radial-gradient(#ffffff, #fdfbf7)',
  },
});
